### ISSUE TITLE
Dock doesn't work with selinux in enforcing mode

### ISSUE THREAD

**Issue by arrfab** [projectatomic/atomic-reactor#132] opened 2015-06-02 13:02 UTC
from audit.log : 
type=AVC msg=audit(1433249265.214:440): avc:  denied  { connectto } for  pid=21917 comm="dock" path="/run/docker.sock" scontext=system_u:system_r:svirt_lxc_net_t:s0:c713,c933 tcontext=system_u:system_r:docker_t:s0 tclass=unix_stream_socket

So either writing a custom selinux policy, or trying to change the scontext would probably work. I'll investigate it and will post the workaround

**Comment by TomasTomecek** [comment] 2015-06-02 13:07
What is the official way to handle this? Get proper rules to `selinux-policy`? Or should we ship our own rules and enforce them in rpm post install scriptlet? Or even put some stuff into our code?

**Comment by arrfab** [comment] 2015-06-02 15:33
The following .te (to be compiled into a selinux .pp module) works : 

```
module dock 1.0;
require {
	type docker_t;
	type svirt_lxc_net_t;
	class unix_stream_socket connectto;
}
#============= svirt_lxc_net_t ==============
allow svirt_lxc_net_t docker_t:unix_stream_socket connectto; 
```
Once you have that .te in a specific staging directory, you need compile and install te produced .pp, you  just need to (tested on CentOS 7) : 
```
yum install selinux-policy-devel -y
make -f /usr/share/selinux/devel/Makefile
semodule -i dock.pp
```

**Comment by jpopelka** [comment] 2015-08-12 10:47
Closing as duplicate of #206

**Closed by jpopelka** 2015-08-12 10:47 UTC
Labels: bug
